apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "roar-db.name" . }}
  labels:
    app: {{ template "roar-db.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "roar-db.name" . }}
  template:
    metadata: 
      labels:
        app: {{ template "roar-db.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: bclaster/roar-db-image:v1
        imagePullPolicy: Always
        ports:
        - name: {{ .Values.deployment.ports.name }}
          containerPort: {{ .Values.deployment.ports.containerPort }}
        env:
          {{- include "roar-db.environment-values" . | indent 10 }}
       

