# Default values for roar-db-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
deployment:
  ports:
    name: mysql
    containerPort: 3306
  env:
    MYSQL_DATABASE: "registry"
    MYSQL_PASSWORD: "admin"
    MYSQL_ROOT_PASSWORD: "root+1"
    MYSQL_USER: "admin"
service:
  frontendPortName: "mysql"
  externalPort: 3306
  internalPort: 3306

